### Arange() - Used to create Numpy Array
- It creates one dimensional array

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [5]:
a = np.arange(1, 10, dtype = 'float64')
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
a = np.arange(1, 10, 2, dtype = 'complex')
a

array([1.+0.j, 3.+0.j, 5.+0.j, 7.+0.j, 9.+0.j])