In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a+3

array([4, 5, 6, 7])

In [4]:
a-1

array([0, 1, 2, 3])

In [5]:
a*2

array([2, 4, 6, 8])

In [9]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [7]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [10]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [19]:
a1 = np.array([5,6,7,8])
a1

array([5, 6, 7, 8])

In [20]:
a+a1

array([ 6,  8, 10, 12])

In [21]:
a-a1

array([-4, -4, -4, -4])

In [22]:
a*a1

array([ 5, 12, 21, 32])

In [11]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
b+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
b-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [15]:
b*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [16]:
b/4

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

In [17]:
b%2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [18]:
b**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [23]:
b1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
b1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
b+b1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [25]:
b-b1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
b*b1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [27]:
b%b1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [28]:
b**b1

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]], dtype=int32)