In [1]:
# NumPy is a Python Library / module which is used for scientific calculations. 

In [2]:
import numpy as np

### Creating an Array 

In [3]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [4]:
a = np.array((1, 2, 3, 4, 5))
a

array([1, 2, 3, 4, 5])

In [5]:
# The type of the array can also be explicitly specified at the time of creation :
a = np.array([1, 2, 3, 4, 5], dtype=float)
a

array([1., 2., 3., 4., 5.])

In [6]:
# if there is a single string in the object all the elments will be converted to string
# else complex all convert to complex
# else no string but float and int and bool all converted to float
# else combination int and bool all converted to int

### Examples:

In [7]:
a=np.array([1,'raj', 2, 3, 4])  
a

array(['1', 'raj', '2', '3', '4'], dtype='<U11')

In [8]:
a = np.array([1, True, 3, 4+9j, 1,5])   
a

array([1.+0.j, 1.+0.j, 3.+0.j, 4.+9.j, 1.+0.j, 5.+0.j])

In [9]:
a = np.array([1.0, 3, False, 0, -4, 1]) 
a

array([ 1.,  3.,  0.,  0., -4.,  1.])

In [10]:
a = np.array([1, True, False, 2, 4, -5]) 
a

array([ 1,  1,  0,  2,  4, -5])

### Two dimensional array

In [11]:
b=np.array([[1,2,3],[4,5,6]]) 
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b=np.array([(1,2,3),(4,5,6)]) 
b

array([[1, 2, 3],
       [4, 5, 6]])