### Broadcasting
- In order to broadcast, The Size of the trailing(from right side) axes for both array in operation must be either be the same or one of them must be one.

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b = np.array([5,6,7,8])
b

array([5, 6, 7, 8])

In [4]:
print(a.shape)
print(b.shape)
# Shape of these two array is same

(4,)
(4,)


In [5]:
a+b # shape is same

array([ 6,  8, 10, 12])

In [6]:
c = np.array([2]) 
c

array([2])

In [7]:
a + c # shape of c is one

array([3, 4, 5, 6])

In [8]:
d = np.array([3,4,5])
d

array([3, 4, 5])

In [9]:
a + d # shape is not same

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [10]:
a

array([1, 2, 3, 4])

In [11]:
e = np.arange(1,9).reshape(2,4)
e

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a + e
# Shape of 
# a = 2 X 4
# e = 1 X 4
# from right side 4 and 4, same.
# 2 and 1, e size is one   

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [13]:
f = np.arange(1,13).reshape(3,4)
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
e + f
# Shape of 
# e = 2 X 4
# f = 3 X 4
# from right side 4 and 4, same.
# 2 and 3, not same then error.

ValueError: operands could not be broadcast together with shapes (2,4) (3,4) 