In [1]:
import numpy as np

### Synatx
- eye(N, M=None, k=0, dtype='float', order='C')

In [2]:
a = np.eye(4) 
# Here n=4 and M is not specified, If it is not specied it is same as N.
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
a = np.eye(4,4)  # it is same as np.eye(4) 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
a = np.eye(4,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [5]:
a = np.eye(4,4,k=1) 
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [6]:
a = np.eye(4,4,k=2) 
a

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
a = np.eye(4,4,k=-1) 
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [8]:
a = np.eye(4,4,k=-2) 
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [9]:
a = np.eye(4,4,k=4) 
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
a = np.eye(4,4,dtype='int') 
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## Identity() Function
### syntax
- identity(n, dtype=None)
- it is same as eye() but difference is that it always create square matrix.

In [13]:
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
a = np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
a = np.identity(3, dtype='int')
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
a = np.identity(3, dtype='complex')
a

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])