## flatten() and ravel()

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [4]:
a.flatten(order='F')

array([1, 4, 2, 5, 3, 6])

### ravel()

In [5]:
b = np.array([[10,20,30],[40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [6]:
np.ravel(b)

array([10, 20, 30, 40, 50, 60])

In [7]:
np.ravel(b,order='F')

array([10, 40, 20, 50, 30, 60])

In [8]:
b.ravel()

array([10, 20, 30, 40, 50, 60])