## Indexing

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a[0]

1

In [4]:
a[2]

3

In [5]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [6]:
a[1]=10
a

array([ 1, 10,  3,  4])

In [7]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
b[1]

array([4, 5, 6, 7])

In [9]:
b[1][2]

6

In [10]:
b[1,2] # this is same as above

6

## slicicng

In [11]:
a

array([ 1, 10,  3,  4])

In [12]:
a[0:3]

array([ 1, 10,  3])

In [13]:
a[:]

array([ 1, 10,  3,  4])

In [14]:
a[:3:2]

array([1, 3])

In [15]:
a[-1]

4

In [16]:
a[-2:0:-1]

array([ 3, 10])

In [17]:
a[-3:3]

array([10,  3])

In [18]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
b[0:2,2:4]

array([[2, 3],
       [6, 7]])

In [21]:
b[2,0:2]

array([8, 9])