In [1]:
import numpy as np

In [2]:
## help(np.insert)
## insert(arr, obj, values, axis=None)
## obj -> index

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
np.insert(a,1,10)

array([ 1, 10,  2,  3,  4])

In [5]:
np.insert(a,1,[10,20,30])

array([ 1, 10, 20, 30,  2,  3,  4])

In [6]:
np.insert(a,(1,4),10)

array([ 1, 10,  2,  3,  4, 10])

In [7]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.insert(b,1,20,axis=0)

array([[ 0,  1,  2],
       [20, 20, 20],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
np.insert(b,1,20,axis=1)

array([[ 0, 20,  1,  2],
       [ 3, 20,  4,  5],
       [ 6, 20,  7,  8],
       [ 9, 20, 10, 11]])

In [10]:
np.insert(b,2,[20,30,40],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [20, 30, 40],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.insert(b,0,[20,30,40,50],axis=1)

array([[20,  0,  1,  2],
       [30,  3,  4,  5],
       [40,  6,  7,  8],
       [50,  9, 10, 11]])

In [12]:
np.insert(b,3,[[20],[30],[40],[50]],axis=1)

array([[ 0,  1,  2, 20, 30, 40, 50],
       [ 3,  4,  5, 20, 30, 40, 50],
       [ 6,  7,  8, 20, 30, 40, 50],
       [ 9, 10, 11, 20, 30, 40, 50]])

In [13]:
np.append(b,[[11,22,33]],axis=0) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [11, 22, 33]])

In [14]:
np.append(b,[[20],[30],[40],[50]],axis=1)

array([[ 0,  1,  2, 20],
       [ 3,  4,  5, 30],
       [ 6,  7,  8, 40],
       [ 9, 10, 11, 50]])

In [15]:
a

array([1, 2, 3, 4])

In [16]:
np.delete(a,1)

array([1, 3, 4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.delete(b,2,axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11]])

In [20]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.delete(b,2,axis=1)

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])