In [1]:
import numpy as np

In [7]:
a = np.random.randn()
a

-1.0401195313870408

In [16]:
a = np.random.randn(5)
a

array([ 2.32583305,  0.70792771, -0.12018054, -0.12476498,  1.09135816])

In [15]:
a = np.random.randn(3,4)
a

array([[-0.13851775,  0.70363823, -0.54974663, -1.35497733],
       [-0.48032156, -0.25930882,  1.33010686,  0.27146934],
       [-0.22365741, -1.23050655, -0.07168185,  1.8227226 ]])

In [19]:
a = np.random.ranf(3)
a

array([0.46678453, 0.30395195, 0.20175407])

In [23]:
a = np.random.randint(1,10,30)
a

array([4, 8, 9, 6, 7, 1, 6, 3, 9, 7, 8, 5, 9, 4, 4, 1, 6, 8, 9, 3, 3, 6,
       5, 2, 7, 5, 3, 1, 4, 6])

In [24]:
a = np.random.randint(1,20,30).reshape(6,5)
a

array([[11, 10,  8, 19,  5],
       [ 7,  5,  1,  5,  9],
       [15,  7, 19, 17,  7],
       [ 6, 14, 17,  7, 16],
       [11,  2, 19, 11,  2],
       [ 3,  8,  8,  3,  6]])