## reshape() and resize()

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
np.reshape(a,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# OR
a.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a  # reshape returns the reshaped array but doesn't change the shape of the original array

array([1, 2, 3, 4, 5, 6])

In [6]:
b = np.arange(12).reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### resize()

In [7]:
c = np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [8]:
np.resize(c,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
# OR
c.resize((3,2))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
c # resize() chages the shape of the original array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.resize(c,(3,4))

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [12]:
np.resize(c,(5,4))

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6],
       [1, 2, 3, 4],
       [5, 6, 1, 2]])