## statistics

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
a.sum()

15

In [5]:
a.max()

5

In [6]:
a.min()

1

In [7]:
a.mean()

3.0

In [8]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [9]:
np.std(a)

1.4142135623730951

In [10]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [11]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
b.sum()

78

In [13]:
b.max()

12

In [14]:
b.min()

1

In [15]:
b.mean()

6.5

In [17]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [18]:
np.std(b)

3.452052529534663

In [20]:
b.sum(axis=0)

array([15, 18, 21, 24])

In [21]:
b.sum(axis=1)

array([10, 26, 42])