## transpose() and swapaxes() Function

In [1]:
import numpy as np

In [2]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
# Or by specifying index 
np.transpose(a,(1,0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
np.transpose(a,(0,1)) # it is same as original array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Or we can use
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
b = np.arange(1,25).reshape(2,3,4)
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [9]:
b.shape

(2, 3, 4)

In [10]:
np.transpose(b)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [11]:
np.transpose(b).shape

(4, 3, 2)

In [12]:
# shape (2,3,4) => (0,1,2)
# if we want change shape to (3,2,4) => (1,0,2) 

In [13]:
np.transpose(b,(1,0,2))

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [14]:
np.transpose(b,(1,0,2)).shape

(3, 2, 4)

### swapaxes()

In [15]:
c = np.array([[1,2,3,4]])
c

array([[1, 2, 3, 4]])

In [16]:
np.swapaxes(c,0,1) # we can specify the axis 0,1 OR 1,0 the meaning is remain same.

array([[1],
       [2],
       [3],
       [4]])

In [17]:
np.swapaxes(c,1,0)

array([[1],
       [2],
       [3],
       [4]])

In [18]:
d = np.array([[10,20,30],[40,50,60]])
d

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
np.swapaxes(d,0,1)

array([[10, 40],
       [20, 50],
       [30, 60]])